//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FabriPipa.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PipasEntities : DbContext
    {
        public PipasEntities()
            : base("name=PipasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBClientes> TBClientes { get; set; }
        public virtual DbSet<TBFornecedores> TBFornecedores { get; set; }
        public virtual DbSet<TBItens> TBItens { get; set; }
        public virtual DbSet<TBPedidos> TBPedidos { get; set; }
        public virtual DbSet<TBProdutos> TBProdutos { get; set; }
        public virtual DbSet<TBTipoDocumento> TBTipoDocumento { get; set; }
        public virtual DbSet<TBTipoUsuario> TBTipoUsuario { get; set; }
        public virtual DbSet<TBUsuarios> TBUsuarios { get; set; }
    }
}
