//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FabriPipa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBClientes
    {
        public int IdCliente { get; set; }
        public int IdTipoDoc { get; set; }
        public string NumDoc { get; set; }
        public string NmCliente { get; set; }
        public string Telefone { get; set; }
        public string Endereco { get; set; }
        public System.DateTime DtInclusao { get; set; }
        public System.DateTime DtAlteracao { get; set; }
    }
}
