//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FabriPipa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBPedidos
    {
        public int IdPedido { get; set; }
        public int IdCliente { get; set; }
        public System.DateTime DtPedido { get; set; }
        public string NumPedido { get; set; }
        public System.DateTime DtInclusao { get; set; }
        public Nullable<System.DateTime> DtAlteracao { get; set; }
    }
}
