//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FabriPipa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBUsuarios
    {
        public int IdUsuario { get; set; }
        public int IdTipoUsuario { get; set; }
        public int IdUsuarioAlteracao { get; set; }
        public string NmUsuario { get; set; }
        public string NmLogin { get; set; }
        public string Senha { get; set; }
        public bool BtAtivo { get; set; }
        public System.DateTime DtInclusao { get; set; }
        public System.DateTime DtAlteracao { get; set; }
    }
}
